// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PROJECTKPL.API.Data;

#nullable disable

namespace PROJECTKPL.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260604102151_UpdateModel")]
    partial class UpdateModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PROJECTKPL.API.Models.Obat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Harga")
                        .HasColumnType("int");

                    b.Property<string>("NamaObat")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StatusObat")
                        .HasColumnType("int");

                    b.Property<int>("Stok")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Obat");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Harga = 5000,
                            NamaObat = "Paracetamol 500mg",
                            StatusObat = 0,
                            Stok = 50
                        },
                        new
                        {
                            Id = 2,
                            Harga = 12000,
                            NamaObat = "Amoxicillin 250mg",
                            StatusObat = 1,
                            Stok = 8
                        },
                        new
                        {
                            Id = 3,
                            Harga = 3000,
                            NamaObat = "Antasida",
                            StatusObat = 2,
                            Stok = 0
                        });
                });

            modelBuilder.Entity("PROJECTKPL.API.Models.Pelanggan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NoTelp")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Umur")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Pelanggan");
                });

            modelBuilder.Entity("PROJECTKPL.API.Models.Pesanan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IdPesanan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Jumlah")
                        .HasColumnType("int");

                    b.Property<int>("MetodePengambilan")
                        .HasColumnType("int");

                    b.Property<int>("ObatId")
                        .HasColumnType("int");

                    b.Property<int>("PelangganId")
                        .HasColumnType("int");

                    b.Property<int>("Pembayaran")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ObatId");

                    b.HasIndex("PelangganId");

                    b.ToTable("Pesanan");
                });

            modelBuilder.Entity("PROJECTKPL.API.Models.Pesanan", b =>
                {
                    b.HasOne("PROJECTKPL.API.Models.Obat", "Obat")
                        .WithMany()
                        .HasForeignKey("ObatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PROJECTKPL.API.Models.Pelanggan", "Pelanggan")
                        .WithMany("RiwayatPembelian")
                        .HasForeignKey("PelangganId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Obat");

                    b.Navigation("Pelanggan");
                });

            modelBuilder.Entity("PROJECTKPL.API.Models.Pelanggan", b =>
                {
                    b.Navigation("RiwayatPembelian");
                });
#pragma warning restore 612, 618
        }
    }
}
